### ISSUE TITLE
sb EWT

### ISSUE THREAD

**Issue by sc29740314** [laoshuikaixue/ewt360#1]
垃圾垃圾垃圾，自己不用就开源，豆瓣零分豆瓣零分豆瓣零分豆瓣零分豆瓣零分豆瓣零分豆瓣零分豆瓣零分豆瓣零分豆瓣零分豆瓣零分豆瓣零分豆瓣零分豆瓣零分豆瓣零分，圈钱EWT真的无语，垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT，580绝对不会付的，课还跟个*************************************一样，课好点580就算了，内容和作业都和*****************************************一样，还有LAOSHUIKAIXUE，这里不多说，总之，**垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT垃圾EWT**

**Comment by laoshuikaixue** [comment]
你的issue是没有意义的 请不要创建类似的issue。
